# Site Settings
title: Markus Reiter
email: me@reitermark.us
description: >
  I am Markus Reiter, currently studying computer science
  at the University of Innsbruck. My fields of interest
  include automation and graphic, type and web design.
baseurl: ''
url: https://reitermark.us
twitter_username: reitermarkus
github_username:  reitermarkus
linkedin_username:  markusreiter
timezone: Europe/Vienna

# Build Settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-spaceship

# Exclusions
exclude:
  - '.gitignore'
  - 'ReadMe.md'
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'

collections:
  projects:
    output: false

excerpt_separator: <!--more-->


jekyll-spaceship:
  mermaid-processor:
    mode: pre-fetch
